server:
  port: 8081
#server.address=192.168.16.11
spring:
  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jfinal_demotwo?useUnicode=true&&amp;characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true
#邮箱
  mail:
    host: smtp.126.com
    username: suchengkuaile@126.com
    password: uu787679
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
logging:
  config: classpath:logback-spring.xml


  #spring.thymeleaf.content-type=text/html

  # MVC
  #spring.mvc.view.prefix=/WEB-INF/views/
  #spring.mvc.view.suffix=.jsp
  #spring.mvc.view.cache=false



