server:
  port: 8081
#  address: ghj.oo.com
#server.address=192.168.16.11
spring:
  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  main:
    allow-bean-definition-overriding: true   #当遇到同样名字的时候，是否允许覆盖注册
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jfinal_demotwo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true
#邮箱
  mail:
    host: smtp.126.com
    username: suchengkuaile@126.com
    password: uu787679
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#rabbitmq
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: susu
    password: 123456
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10 #最大的并发
        acknowledge-mode: manual #签收的模式 手工签收
        prefetch: 1 #节流的

#rabbitmq
logging:
  config: classpath:logback-spring.xml


  #spring.thymeleaf.content-type=text/html

  # MVC
  #spring.mvc.view.prefix=/WEB-INF/views/
  #spring.mvc.view.suffix=.jsp
  #spring.mvc.view.cache=false



